### ISSUE TITLE
Configure Build System

### ISSUE THREAD

**Issue by alexv-anderson** [bcroden/QuizDeck-Server#1]
Gather the libraries and create the build scripts which are needed to successfully build the server's source code.

**Comment by alexv-anderson** [comment]
@bcroden, @rxm033, will the build tools we use for the server need to work with the build/unit test/coverage tools that are used for the client? If not, is it okay for me to setup a ANT script to build the Java source everything or will we need another tool to get the database started and REST started? @CadeG, do you have any thoughts?

**Comment by alexv-anderson** [comment]
@CadeG the version of Jython needed is 2.7.0. I used the installer to get Jython setup on my machine. When I both compile and run the java source code, I have to add `${JYTHON_HOME}/jython.jar` to the classpath. The Excel library is `xlsxwriter`. its install documentation is [here](http://xlsxwriter.readthedocs.org/getting_started.html)

**Comment by bcroden** [comment]
for gradle you should just need to add this to the dependencies list.
compile('org.python:jython-standalone:2.7.0')

**Comment by CadeG** [comment]
Sweet, I'll let you know if I get the ws built tonight

**Comment by alexv-anderson** [comment]
Just pushed a simple program which uses Jython to print some stuff. This is not the package structure I want to use for the Java source files, but it is enough to get test the build and run environments. It should work so long as you have `src/python` listed as a runtime dependency in the classpath. The project structure takes some sugar coating for Intellij to swallow it. I'll post steps on how to do it in later today.

**Comment by alexv-anderson** [comment]
Added a [walk through](https://github.com/bcroden/QuizDeck-Server/wiki) to the wiki of how to setup Intellij to locally run the project with the example program I pushed earlier today.

**Comment by alexv-anderson** [comment]
@CadeG is there a reason why the build scripts set the source level the source code to Java 6? Is it possible to get it up to Java 8?

**Comment by CadeG** [comment]
I don't see that in any of the scripts.  Gradle is set for target
compatibility with 1.8

**Comment by alexv-anderson** [comment]
That is odd. I pulled your changes, and now Intellij is griping about my use of Java syntax which is greater than Java 6. There must be a setting somewhere that I missed. Thanks anyways

**Comment by bcroden** [comment]
I did some cleanup for git so that we are including the gradle runtime and excluding the build and tmp folders

**Comment by alexv-anderson** [comment]
[Here](https://github.com/hierynomus/jython-gradle-plugin) is a Gradle plugin that I mention which should be able to handle XlsxWriter. I push an initial try at using it, but I think that I am declaring the dependency incorrectly.

**Comment by alexv-anderson** [comment]
I have exhausted every avenue I know of to get Gradle to add Jython libraries as dependencies, but it has been no good. Brandon found a JavaScript library ([JS-XLSX](https://github.com/SheetJS/js-xlsx)) which should do everything that we want. In short, we are off-loading Excel generation to the client and performing all of the analysis on the server, so right now we do <i>not</i> need Jython as a dependency in the Gradle script.
