### ISSUE TITLE
Create connection to existing Redis Database

### ISSUE THREAD

**Issue by CadeG** [bcroden/QuizDeck-Server#30]

**Comment by bcroden** [comment]
Manually Parse the Redis uri provided by the Heroku Plugin into 3 new Heroku environment variables.

The Heroku Provided uri is in the following format: `redis://rediscloud:password@host:port`

So the 3 env vars should be:

```
REDIS_HOST = host
REDIS_PASSWORD = password
REDIS_PORT = port
```

Then Update the Procfile to use:

```
--spring.redis.host=$REDIS_HOST
--spring.redis.port=$REDIS_PORT
--spring.redis.password=$REDIS_PASSWORD
```

Then delete the Java Redis Configuration Class, and the profile from the Procfile.

This should get our App to Connect to Redis

**Comment by CadeG** [comment]
Created environment variables with the appropriate content on the heroku server, connection to redis established (using redis cloud for additional space)
