### ISSUE TITLE
Time Sensitive Unit Tests

### ISSUE THREAD

**Issue by bcroden** [bcroden/QuizDeck-Server#44]
@alexv-anderson Why are we including time sensitive unit tests? 

QuizAccuracyAlgorithmTest.benchmarkAnalysisTime() caused a Travis Build to fail. It worked fine after restarting the build, and I have had no problems with it locally.

Is it wise to include time sensitive tests knowing that Travis is under random load from the open source community at any given time?

**Comment by alexv-anderson** [comment]
The reason for time sensitive unit tests was a preventative measure. Namely to raise red flags when a change caused the analysis algorithms to run slower. I did not realize that Travis was was subject to random load stresses. The timed unit test has been removed as of merge #46.
