### ISSUE TITLE
Quiz Indecisiveness Analysis Algorithm

### ISSUE THREAD

**Issue by alexv-anderson** [bcroden/QuizDeck-Server#5]
Data analysis algorithm with the following outputs.
- Data
  - Time when each response was submitted
  - Total number of guesses submitted by participants
- Graph:
  - Arrival of responses vs time (Scatter Plot)
  - Answer distribution per number of submissions (Bar Chart)

**Comment by alexv-anderson** [comment]
@CadeG I am currently reusing the `AccuracyInput` class for the input to the REST controller for indecisive analysis of a single quiz. Do I need to use a different class? It appears to work, but it may be confusing due to its name. Does it need to be renamed it to something like `QuizAnalysisInput` or do you think that it will be okay as it is?

**Comment by CadeG** [comment]
AccuracyInput should be fine, the input received is specific to the each method in the controller, or at least they should be.  QuizAnalysisInput would probably be the more confusing of the two.  I'd recommend refactoring the name to be QuizAccuracyInput
